---
# Configuration for https://pre-commit.com
# To use: pre-commit run -a
# Or to run every time you commit: pre-commit install
# To update this file: pre-commit autoupdate

repos:

  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-json
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: requirements-txt-fixer

  # Check for spelling
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: ["-L", "tre"]
        exclude: >
            (?x)^(
                .*\.txt|
                .*\.ipynb|
                .*\.html
            )$

 # Format docstrings
  - repo: https://github.com/DanielNoord/pydocstringformatter
    rev: v0.7.3
    hooks:
      - id: pydocstringformatter
        args: ["--style=numpydoc"]

  # Ruff, the Python auto-correcting linter/formatter written in Rust
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
      - id: ruff-format

  # Check types with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports", "--follow-imports", "skip", "--check-untyped-defs"]
        additional_dependencies: [types-PyYAML==6.0.12.9,tokenize-rt==3.2.0]
        exclude: "stata/.*|docs/.*"
...
