---
# Configuration for https://pre-commit.com
# To use: pre-commit run -a
# Or to run every time you commit: pre-commit install
# To update this file: pre-commit autoupdate

repos:

  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-json
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: requirements-txt-fixer

  # Check for spelling
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: ["-L", "tre"]
        exclude: >
            (?x)^(
                .*\.txt|
                .*\.ipynb|
                .*\.html
            )$

  # Upgrade old Python syntax
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  # Autoremoves unused imports
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake

  # Sort includes
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # Format docstrings
  - repo: https://github.com/DanielNoord/pydocstringformatter
    rev: "v0.7.3"
    hooks:
      - id: pydocstringformatter
        args: ["--style=numpydoc"]

  # Black format Python and notebooks
  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black-jupyter

  # Check Python with flake8
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=95
          - --exclude=__init__.py
          - --ignore=E203,W503
        additional_dependencies: [flake8-bugbear, pep8-naming]
        exclude: "docs"

  # Check types with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports", "--follow-imports", "skip", "--check-untyped-defs"]
        additional_dependencies: [types-PyYAML==6.0.12.9,tokenize-rt==3.2.0]
        exclude: "stata/.*|docs/.*"
...
