---
title: "ACRO R Notebook"
output: html_notebook
---

```{r}
# install.packages("haven")
# install.packages("reticulate")
```

## Import Libraries

```{r}
library(haven)   # read .dta
source("../acro.R")  # ACRO
```

## Load Data

```{r}
data = read_dta("../data/test_data.dta")
data = as.data.frame(data)
data = zap_labels(data)  # Stata data files include extra labels

head(data)
```

## Tables

### ACRO Crosstab

```{r}
index = data[, c("year")]
columns = data[, c("grant_type")]
values = data[, c("inc_grants")]
aggfunc = "mean"

table = acro_crosstab(index, columns, values=values, aggfunc=aggfunc)
```

```{r}
table
```

### Add Comments to Output

```{r}
acro_add_comments("output_0", "This is a crosstab on the nursery dataset.")
```

### ACRO Pivot Table

```{r}
index = "grant_type"
values = "inc_grants"
aggfunc = list("mean", "std")

table = acro_pivot_table(data, values=values, index=index, aggfunc=aggfunc)
```

```{r}
table
```

## Linear Models

```{r}
# extract relevant columns
df = data[, c("inc_activity", "inc_grants", "inc_donations", "total_costs")]
# drop rows with missing values
df = df[complete.cases(df), ]
# formula to fit
formula = "inc_activity ~ inc_grants + inc_donations + total_costs"
```

### Fit Linear Model

```{r}
model = lm(formula=formula, data=df)
summary(model)
```

### ACRO Linear Model

```{r}
acro_lm(formula=formula, data=df)
```

## Logit/Probit Models

```{r}
# extract relevant columns
df = data[, c("survivor", "inc_activity", "inc_grants", "inc_donations", "total_costs")]
# drop rows with missing values
df = df[complete.cases(df), ]
# convert survivor to numeric
df = transform(df, survivor = as.numeric(survivor))
# formula to fit
formula = "survivor ~ inc_activity + inc_grants + inc_donations + total_costs"
```

### Fit Logit Model

```{r}
model = glm(formula=formula, data=df, family=binomial(link="logit"))
summary(model)
```

### ACRO Logit Model

```{r}
acro_glm(formula=formula, data=df, family="logit")
```

### Fit Probit Model

```{r}
model = glm(formula=formula, data=df, family=binomial(link="probit"))
summary(model)
```

### ACRO Probit Model

```{r}
acro_glm(formula=formula, data=df, family="probit")
```

### Add Custom Output

```{r}
acro_custom_output("XandY.jpeg", "This output is an image showing the relationship between X and Y")
```

### Rename Output

```{r}
acro_rename_output("output_5", "xy_plot")
```

### Remove Output

```{r}
acro_remove_output("output_3")
```

## Finalise

```{r}
acro_finalise("RTEST", "json")
```

## Use the help function

```{r}
acro_help("acro_pivot_table")
```
