---
package:
  name: acro
  version: "0.4.8"

source:
  url: https://pypi.org/packages/source/a/acro/acro-0.4.8.tar.gz
  sha256: fb4f4fe738bb56385802de27b2984cbba2145d8d00a8c33261ffd2eb6e0e8207

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9
    - lxml
    - matplotlib-base
    - numpy
    - openpyxl
    - pandas >=1.5.0,<2.3
    - PyYAML
    - statsmodels

test:
  imports:
    - acro
  commands:
    - pip check
    - python -c "from acro import ACRO; a = ACRO()"
  requires:
    - pip

about:
  home: https://github.com/AI-SDC/ACRO
  summary: "ACRO: Tools for the Semi-Automatic Checking of Research Outputs"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rpreen
...
