---
name: lint

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.cff'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: pylint
        run: |
          pylint -v --recursive=True acro test --fail-under 10
...
