---
name: Test Python313

on: workflow_dispatch

jobs:
  build:
    name: ${{ matrix.os }}-Python${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.13']

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: venv activate Ubuntu/macOS
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
        run: |
          python -m venv venv-acro
          source ./venv-acro/bin/activate

      - name: venv activate Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          python -m venv venv-acro
          venv-acro\Scripts\activate.bat

      - name: Install acro and pytest
        run: python -m pip install . pytest

      - name: Run pytest
        run: python -m pytest .
...
