---
name: test

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.cff'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install
        run: |
          pip install --upgrade pip
          pip install .[test]

      - name: Generate coverage report
        run: |
          pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
...
